let data = [
    {
        "building": "Mac",
        "room": "314",
        "teacher": "Nadeem Hamid",
        "division": "Computer Science",
        "code": "CSC120",
        "name": "Introduction to Coding",
        "days": "M W F",
        "startingTime": "08:00",
        "endingTime": "08:50",
        "courseID": "1"
    },
    {
        "building": "Mac",
        "room": "214",
        "teacher": "Nadeem Hamid",
        "division": "Computer Science",
        "code": "CSC235B",
        "name": "Physical Computing",
        "days": "M F",
        "startingTime": "15:00",
        "endingTime": "17:00",
        "courseID": "2"
    },
    {
        "building": "Mac",
        "room": "214",
        "teacher": "Nadeem Hamid",
        "division": "Computer Science",
        "code": "CSC235A",
        "name": "Physical Computing",
        "days": "M W F",
        "startingTime": "18:00",
        "endingTime": "21:00",
        "courseID": "5"
    },
    {
        "building": "Mac",
        "room": "117",
        "teacher": "Stephanie Cook",
        "division": "Chemistry",
        "code": "CHM109",
        "name": "General Chemistry",
        "days": "T",
        "startingTime": "10:00",
        "endingTime": "13:00",
        "courseID": "3"
    },
    {
        "building": "Mac",
        "room": "216",
        "teacher": "Rosanne LastName",
        "division": "Chemistry",
        "code": "CHM208",
        "name": "Organic Chemistry",
        "days": "W H F",
        "startingTime": "09:00",
        "endingTime": "10:50",
        "courseID": "4"
    },
    {
        "building": "Evans",
        "room": "216",
        "teacher": "Eric Sands",
        "division": "Political Science",
        "code": "GOV335",
        "name": "Constitutional Law",
        "days": "T H",
        "startingTime": "12:30",
        "endingTime": "13:45",
        "courseID": "5"
    },
    {
        "building": "Evans",
        "room": "115",
        "teacher": "John Hickman",
        "division": "Political Science",
        "code": "GOV217A",
        "name": "Comparative Politics",
        "days": "M W F",
        "startingTime": "14:00",
        "endingTime": "14:50",
        "courseID": "6"
    },
    {
        "building": "Evans",
        "room": "115",
        "teacher": "John Hickman",
        "division": "Political Science",
        "code": "GOV217B",
        "name": "Comparative Politics",
        "days": "M W F",
        "startingTime": "14:00",
        "endingTime": "14:50",
        "courseID": "7"
    },
    {
        "building": "Evans",
        "room": "115",
        "teacher": "John Hickman",
        "division": "Political Science",
        "code": "GOV217C",
        "name": "Comparative Politics",
        "days": "M W F",
        "startingTime": "14:00",
        "endingTime": "14:50",
        "courseID": "8"
    },
    {
        "building": "Evans",
        "room": "115",
        "teacher": "John Hickman",
        "division": "Political Science",
        "code": "GOV217D",
        "name": "Comparative Politics",
        "days": "M F",
        "startingTime": "14:00",
        "endingTime": "14:50",
        "courseID": "9"
    },
    {
        "building": "Evans",
        "room": "115",
        "teacher": "John Hickman",
        "division": "Political Science",
        "code": "GOV217E",
        "name": "Comparative Politics",
        "days": "W F",
        "startingTime": "14:00",
        "endingTime": "14:50",
        "courseID": "10"
    },
    {
        "building": "Laughlin",
        "room": "113",
        "teacher": "Brian Caroll",
        "division": "Communications",
        "code": "COM415",
        "name": "Media Law",
        "days": "T H",
        "startingTime": "12:30",
        "endingTime": "13:45",
        "courseID": "11"
    },
    {
        "building": "Sister's Hall",
        "room": "Studio Dance Room",
        "teacher": "Dylan Bollinger",
        "division": "Music Theatre",
        "code": "THE201",
        "name": "Introduction To Theatrical Dance",
        "days": "T H",
        "startingTime": "16:30",
        "endingTime": "18:00",
        "courseID": "12"
    },
    {
        "building": "Cage",
        "room": "113",
        "teacher": "Cori Theirman",
        "division": "Kinesiology",
        "code": "KIN101",
        "name": "Health and Wellness",
        "days": "W",
        "startingTime": "08:30",
        "endingTime": "09:30",
        "courseID": "13"
    },
    {
        "building": "Green",
        "room": "319",
        "teacher": "Chirstopher Twyman",
        "division": "Business",
        "code": "BUS210",
        "name": "Business Law",
        "days": "T",
        "startingTime": "17:30",
        "endingTime": "20:00",
        "courseID": "14"
    }
]